---
title: "fat-DRG annotation"
output: html_notebook
---

```{r}
rm(list=ls())
library(dplyr)
library(Seurat)
library(reshape2)
library(ggplot2)
library(harmony)

read.10xh5soup = function(data.file, project.name) {
  sc = load10X(data.file)
  sc = autoEstCont(sc)

  count = adjustCounts(sc)
  seurat.obj = CreateSeuratObject(count, min.cell=3, project=project.name, min.features=200)
  seurat.obj$orig.ident = rep(project.name, length(seurat.obj$orig.ident))
  return (seurat.obj)
}

read.10xh5data = function(data.file, project.name) {
  count = Read10X_h5(data.file)
  seurat.obj = CreateSeuratObject(count, min.cell=3, project=project.name, min.features=200)
  seurat.obj$orig.ident = rep(project.name, length(seurat.obj$orig.ident))
  return (seurat.obj)
}
preprocess = function(data) {
  data = NormalizeData(data)
  data = FindVariableFeatures(data, selection.method = 'vst', nfeatures = 2000)
  data = ScaleData(data, features = rownames(data))
  data = RunPCA(data, features = VariableFeatures(data), verbose = F)
  return (data)
}

read.10xdata = function(data.file, project.name, gene.column=2) {
  count = Read10X(data.file, gene.column=gene.column)
  seurat.obj = CreateSeuratObject(count, min.cell=3, project=project.name, min.features=200)
  seurat.obj$orig.ident = rep(project.name, length(seurat.obj$orig.ident))
  return (seurat.obj)
}

transfer.label = function(reference, query) {
  drg.anchors = FindTransferAnchors(reference = reference,
                                    query = query, 
                                    dims=1:50)
  labels = TransferData(anchorset = drg.anchors , 
                        refdata = reference@active.ident, 
                        dims = 1:50)
  query = AddMetaData(query, metadata = labels)
  return (query)
}
```

```{r}
ginty.save = LoadH5Seurat('ginty.h5Seurat')
iwat = read.10xdata('Adipose_Seq/FromCore/01inIWAT_featurebcmatrixfiltered/filtered_feature_bc_matrix/', 'iwat')
ewat = read.10xdata('Adipose_Seq/FromCore/02inEWAT_featurebcmatrixfiltered/filtered_feature_bc_matrix/', 'ewat')
non = read.10xdata('Adipose_Seq/FromCore/03inOTHR_featurebcmatrixfiltered/filtered_feature_bc_matrix/', 'unlabeled')

fat.seq = merge(ewat, c(iwat, non))

```


```{r}
fat.seq[['mt.percent']] = PercentageFeatureSet(fat.seq, pattern='^mt-')
fat.seq = subset(fat.seq, subset = mt.percent < 10)
fat.seq = preprocess(fat.seq)
```

```{r}
ginty.save = FindVariableFeatures(ginty.save, verbose = F)
ginty.save = ScaleData(ginty.save, verbose = F)
ginty.save = RunPCA(ginty.save, npcs=50, verbose = F)
ginty.save = RunUMAP(ginty.save, dims=1:50)
DimPlot(ginty.save, label = T)

```


```{r}
harm.seq = merge(ginty.save, fat.seq)
harm.seq = preprocess(harm.seq)
harm.seq = RunHarmony(harm.seq, 'orig.ident')
harm.seq = RunUMAP(harm.seq, reduction = 'harmony', dims=1:50)
DimPlot(harm.seq, group.by = 'orig.ident')

```

```{r}
fat.harm = subset(harm.seq, subset = orig.ident != 'ginty')
ginty.harm = subset(harm.seq, subset = orig.ident == 'ginty')
```


```{r}
fat.harm = transfer.label(ginty.harm, fat.harm)
DimPlot(fat.harm, group.by = 'predicted.id', label = T)
```


